fixed some ts error
iRoachie/DefinitelyTyped pull request #1
Opened 2017-08-26 16:22 UTC by loopArray

My environment is typescript 2.4.2, which reminds me of the wrong type.
`[ts] JSX element type 'Icon' does not have any construct or call signatures.` 

![001](https://user-images.githubusercontent.com/7822744/29743068-c4d49be0-8abc-11e7-8fbf-b096e52f78f3.png)

This is typescript's hint for the source code, and the return type is `typeof Icon`
![002](https://user-images.githubusercontent.com/7822744/29743101-66b014c6-8abd-11e7-92d0-98a15a47a693.png)

When you add `typeof` changes like my PR, there is no error.
![002](https://user-images.githubusercontent.com/7822744/29743120-c8b7e7a2-8abd-11e7-9210-2adb4bb08fe8.png)

2017-08-27 02:39 UTC, iRoachie commented
@loopArray  How are you importing the Icon?

2017-08-27 09:20 UTC, loopArray commented
Custom Font js file:
```
import { createIconSet } from 'react-native-vector-icons';
import glyphMap from './glyphMap.json';

const iconSet = createIconSet(glyphMap, 'FontSciOne', 'FontSciOne.ttf');

export default iconSet;
export const Button = iconSet.Button;
export const TabBarItem = iconSet.TabBarItem;
export const TabBarItemIOS = iconSet.TabBarItemIOS;
export const ToolbarAndroid = iconSet.ToolbarAndroid;
export const getImageSource = iconSet.getImageSource;
```

In tsx file 
```
import React, { Component } from 'react';
import { Button, View } from 'react-native';
import Icon from 'Components/FontSciOne';

... ...
```

But when I import from `react-native-vector-icons/FontAwesome`, it's not show type error
```
import React, { Component } from 'react';
import { Button, View } from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';
```
It's only in import custom font js file.

2017-08-30 17:38 UTC, iRoachie requested changes
You're correct, thanks for finding this. Can you add a test that checks for this?

Something like this:

```ts
const iconSet = createIconSet({}, 'FontSciOne', 'FontSciOne.ttf');

export const Button = iconSet.Button;
export const TabBarItem = iconSet.TabBarItem;
export const TabBarItemIOS = iconSet.TabBarItemIOS;
export const ToolbarAndroid = iconSet.ToolbarAndroid;
export const getImageSource = iconSet.getImageSource;
```

2017-08-31 11:18 UTC, iRoachie approved these changes

2017-08-31 11:23 UTC, iRoachie commented
Hey the changes are good @loopArray. Could you submit it to DefinitelyTyped? I realize you have the PR set to my fork instead

2017-08-31 14:00 UTC, loopArray commented
Hey, I see that you are the author and bring it to you. I haven't PR to DefinitelyTyped. Let me have a try.

2017-08-31 14:03 UTC, iRoachie commented
Yes that’s correct I am the author. However definitelyTyped is the main repo. What usually happens is that the PR is submitted there then i’m alerted to review it and it gets accepted in

2017-08-31 14:19 UTC, loopArray commented
Thank you for your reply so soon.
I had never done such a complicated PR, this is really a bit difficult for me, can help me it's ok?
[19481](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19481)

2017-08-31 14:35 UTC, iRoachie commented
Yea sure i will help

2017-08-31 14:35 UTC, closed without merging